mark_malicious:
  target:
    device:
      integration: ruckus_wips
  fields:
    bssid:
      required: true
      example: "aa:bb:cc:dd:ee:ff"
      selector:
        text:
    entry_id:
      required: false
      example: "01J8B3FA9X1QGZ..."
      selector:
        config_entry:
          integration: ruckus_wips

unmark_malicious:
  target:
    device:
      integration: ruckus_wips
  fields:
    bssid:
      required: true
      example: "aa:bb:cc:dd:ee:ff"
      selector:
        text:
    entry_id:
      required: false
      example: "01J8B3FA9X1QGZ..."
      selector:
        config_entry:
          integration: ruckus_wips
